engines:
  eslint:
    enabled: true
  scss-lint:
    enabled: true
    checks:
      Comment:
        enabled: false
      StringQuotes:
        enabled: false
      VendorPrefix:
        enabled: false
  fixme:
    enabled: true
  duplication:
    enabled: true
    config:
      languages:
      - javascript:
      - php:
  phpmd:
    enabled: true
    checks:
      Naming/ShortVariable:
        enabled: false
ratings:
  paths:
    - "app/scss/**.scss"
exclude_paths:
    - "gulpfile.babel.js"
