language: node_js
sudo: required
dist: trusty
addons:
  firefox: "latest"
  apt:
    sources:
      - google-chrome
    packages:
      - google-chrome-stable
  sauce_connect: true
node_js:
  - "node"
cache:
  yarn: true
  directories:
    - node_modules
    - bower_components
install:
  - sudo rm -rf /home/travis/.cache/yarn
  - npm install -g bower web-component-tester
  - yarn global add gulp-cli
  - yarn install
  - bower install
before_script:
  - yarn run lint
script:
  - xvfb-run yarn run test:local
  - xvfb-run yarn run test:sauce
  - xvfb-run yarn run test:integration
after_success:
  - chmod +x scripts/deploy.sh
  - ./scripts/deploy.sh
