language: node_js
os: linux
dist: bionic
addons:
  chrome: stable
node_js:
  - "node"
  - "9"
  - "8"
jobs:
  allow_failures:
    - node_js: "node"
cache:
  yarn: true
  directories:
    - node_modules
    - bower_components
install:
  - yarn --version
  - npm install -g bower web-component-tester
  - yarn install
  - bower install
before_script:
  - yarn run lint
script:
  - xvfb-run wct -l chrome
