language: node_js
sudo: required
dist: trusty
addons:
  firefox: "latest"
  apt:
    sources:
      - google-chrome
    packages:
      - google-chrome-stable
node_js:
  - "node"
cache:
  yarn: true
  directories:
    - node_modules
    - bower_components
install:
  - npm install -g bower web-component-tester
  - yarn install
  - bower install
before_script:
  - yarn run lint
script:
  - xvfb-run yarn run test:local
  - xvfb-run yarn run test:sauce
  - xvfb-run yarn run test:integration
after_success:
  - find build/es5-bundled/ -name '*' -type f -exec curl -u $FTP_USER:$FTP_PASSWORD --ftp-create-dirs -T {} ftp://home645633144.1and1-data.host/public_html_test/{} \;
env:
  global:
  - secure: Kp9mZ8a9u6QDnIFVl9C9Q5yDKAi64RPLExhZKD6FO45Vg+ql7kpMKVxMTY9N85Xg/nDfy8lmhS0GV0vCWKG/JSBA188PVNzu0czovIJj7z6OvaQ0Di9450Vmc8BaK33fp/Unbh5Cfhc6bm+1zNpHMSYff5cipkOERE+WIF88C+DoEcSyePjHtXU8JWe2Kvra0H7X0Po251v8DMaYUKAmNiKaz0HN9sypwqBgvYT1EC1Jun6kvL5WucnDUCsp0ToUbOaV9Hacw/7V2Wyqwo39ZEcB3X1ua2BPwSqtBaWP9/bRNTNGG/lLNr2unqgk7w1Vo3foYJ3IJZUZk2eT3ILja5h8O8T02MmaGc+0706Goxxf0S2740cOmUHwIehtMWO5pJ/YmXZP1fRnr2nWK2+625ZSgRB1BCbcBAXy/2CXNuybe4jAd75qGmTFCw54wjfLsUEx6gfPqRqErMa74A3T/GoHsLN105dHiS2IfwulYK+0Ww4bVSrgNNrTdkUmqeg3ZzLE2o5aEkqLuFL+FWoewCZeCIoNtgoVGlOEYZ1oKMd8HiOne2QtgmNL1IuH2hoKgXUMMoDl25Sq4Z9FJgH2MjLdXBlhvSqoLeqIlUzJM8ev6ih868X6cb4EhufjPCeC+QlyIbMfGmfk0dodRP5Q/g8gf6FzqmXdgICMFH2fCJY=
  - secure: spSD2HUBuqlEiL2Xxk5LjHya/NYnMYCVd/th7WnLNbVFHZy/kW1q12iq3Fml02XAspamY7ceWghjGp9gbuNkHCZxACHVTC+nKNo7TI0BYRSRa1kzwENN7fZSak1O7YULq4yw+Day7pojFXoKNhY5F0o77ngf+Edjd4zpksmW7V0w9jWbm5qYBLUo/Fd5DkJ9IXbDFV/byWeWgz2wWbmon9NqxTZpckJenStzzftUpmSk1nny/x6p5zyN5DSasizcaT0c5+Fbxix88IIQp51zanUIDpF5JaLm6revkj86LvBWz7MW3FSC4SCVqK3W3rqMD7EQjULkvjzzirQMzHacwWV0rhawjWjfIgCOiVXgj2BLDB7WqaUNwKz0tEHdgjFmPyDgU//Ulc9gB9Rzd7P4bBdyMrhdLK9c8sqgrDaEYExhhXSp/RdWGsJ8+asYMno1LDEBEwOeOzVSWT48/uPbzGPSkBdM6p/TnT46iJkRogxv5AUesj/cjKuHPnap0F3+us6pB0IZU4UvHVcQMPyQs6pflQwacfcZofDTxHS3jcwhvikzqqt//mOq8ppABDEX4EupunO6ygt/v43LuDe1n2Vl7ML4mEGqlTUGwEkiSkibNJpULynZ+g5TlMakUYoVIxsOykLfo310j+sf0vB7FQb3ungFaX2ezELjZ2K3yE0=
