language: node_js
sudo: required
dist: trusty
addons:
  firefox: "latest"
  apt:
    sources:
      - google-chrome
    packages:
      - google-chrome-stable
  sauce_connect:
    username: "patkub"
  jwt:
    secure: "kTuklWBBYM8iRCYC193t0j9eHMEXCOnSZPgC88AG6rcZPlrDISLOJmOqk/MuaeMD4I64T1/0cSuYW7zkAiCjnGEYuJ0ksWchdlqEBgnuk4LgB5RRCe8bGlANdrDCeLJKJC4pfuyIGdNlANkrx/xZKmZ+K2MBnwbPivYEiVUqGgp3B95m5u7Fbj5uZIqiP8AEJl/gsjOJy2yco0nGewm6Bg8ommb370Bu3py3D7xziqhZe9w+vsqZ3yrVILamuSIM8JQ+4EzP4XhDboxEgVx92zWxIu3y2xe5bZ3t7Bp+pj4PpoyH4FsiLvfl3OYWzsWgeZ0UgwvZCXcs8MSCoE0EdRRzb028rntrYDmrCWPlk1ug/pbJTyxaIZBx4kVIeReDdJJ5tNlnPYyA7uUHvBvU4vR9EA9GG943z5nP46KRVoSE7/aJZlodfRvw4XxAFvohc0HqvMd8RpiL8hixAcYGdf1G0syo/3JHsXogMHlahhGtY7nD29UDClj+WooR6UmXpfz/Iet5xSEthYHz3nXkE/lMfdstxyAh26BS8wrP8QkfkrylXng67XCjiyGWl4BH5+Fhw6U4FiRrR2+mk+1iatyi/ZcJ37qZMS0MjckaycS12wbqMJv6ihZTZ5RW3WGDqbJkyk2YDOuNa+HleY9ZLqS5scjTiCYWgXMSVK/FncE="
node_js:
  - "node"
  - "6"
cache:
  yarn: true
  directories:
    - node_modules
    - bower_components
install:
  - npm install -g bower web-component-tester
  - yarn install
  - bower install
before_script:
  - yarn run lint
script:
  - xvfb-run yarn run test
  - xvfb-run yarn run test:integration
  - if [ "${TRAVIS_PULL_REQUEST}" = "false" ]; then wct -s 'windows 10/microsoftedge@14' -s 'windows 8.1/internet explorer@11' -s 'os x 10.11/safari@9' -s 'macos 10.12/safari@10' -s 'Linux/chrome@41'; fi
