language: node_js
sudo: required
dist: trusty
addons:
  firefox: "latest"
  apt:
    sources:
      - google-chrome
    packages:
      - google-chrome-stable
node_js:
  - "node"
  - "6"
cache:
  yarn: true
  directories:
    - node_modules
    - bower_components
install:
  - npm install -g bower web-component-tester
  - yarn install
  - bower install
before_script:
  - yarn run lint
script:
  - xvfb-run yarn run test
  - xvfb-run yarn run test:integration
  - if [ "${TRAVIS_PULL_REQUEST}" = "false" ]; then wct; fi
