language: node_js
sudo: required
dist: trusty
addons:
  firefox: "latest"
  apt:
    sources:
      - google-chrome
    packages:
      - google-chrome-stable
node_js:
  - "node"
  - "6"
cache:
  yarn: true
  directories:
    - node_modules
install:
  - yarn install
before_script:
  - npm run lint
script:
  - xvfb-run npm run test
  - xvfb-run npm run test:integration
