language: node_js
sudo: required
dist: trusty
addons:
  firefox: "latest"
  apt:
    sources:
      - google-chrome
    packages:
      - google-chrome-stable
node_js:
  - "node"
  - "6"
cache:
  yarn: true
  directories:
    - node_modules
    - bower_components
install:
  - npm install -g bower
  - yarn install
  - bower install
before_script:
  - yarn run lint
script:
  - xvfb-run yarn run test
  - xvfb-run yarn run test:integration
after_success:
  - bash <(curl -s https://codecov.io/bash) || echo "Codecov did not collect coverage reports"
