# Test against the latest version of this Node.js version
environment:
  nodejs_version: "6"

# Install scripts. (runs after repo cloning)
install:
  # install modules
  - npm install -g bower web-component-tester
  - yarn global add gulp-cli
  - yarn install
  - bower install

# Post-install test scripts.
test_script:
  # Output useful info for debugging.
  - node --version
  - yarn --version
  # run tests
  - yarn run lint
  - yarn run test:integration
  
# Don't actually build.
build: off
