version: 2
jobs:
  install:
    docker:
      - image: circleci/node:6
    steps:
      - checkout
      - restore_cache:
          keys:
            - cache-install
      - run:
          name: npm-install-global
          command: 'npm install -g bower web-component-tester'
      - run:
          name: yarn-install-global
          command: 'yarn global add gulp-cli'
      - run:
          name: yarn-install
          command: 'yarn install'
      - run:
          name: bower-install
          command: 'bower install'
      - persist_to_workspace:
          root: /tmp/workspace
          paths:
            - ~/.cache/yarn
            - node_modules
            - bower_components
      - save_cache:
          key: cache-install
          paths:
            - ~/.cache/yarn
            - node_modules
            - bower_components
  lint:
    requires:
      - install
    docker:
      - image: circleci/node:6
    steps:
      - attach_workspace:
          at: /tmp/workspace
      - run: yarn run lint
  test:
    requires:
      - install
    docker:
      - image: circleci/node:6
    steps:
      - attach_workspace:
          at: /tmp/workspace
      - run: yarn run test:integration
workflows:
  version: 2
  build_and_test:
    jobs:
      - install
      - lint
      - test
