version: 2
jobs: 
  lint:
    docker:
      - image: circleci/node:6
    steps:
      - checkout
      - restore_cache:
          keys:
            - cache-install
      - run:
          name: node-version
          command: 'node --version'
      - run:
          name: npm-version
          command: 'npm --version'
      - run:
          name: yarn-version
          command: 'yarn --version'
      - run:
          name: npm-install-global
          command: 'sudo npm install -g bower web-component-tester'
      - run:
          name: yarn-install-global
          command: 'sudo yarn global add gulp-cli'
      - run:
          name: yarn-install
          command: 'yarn install'
      - run:
          name: bower-install
          command: 'bower install'
      - save_cache:
          key: cache-install
          paths:
            - ~/.cache/yarn
            - node_modules
            - bower_components
      - run: yarn run lint
  test:
    docker:
      - image: circleci/node:6
    steps:
      - checkout
      - restore_cache:
          keys:
            - cache-test
      - run:
          name: node-version
          command: 'node --version'
      - run:
          name: npm-version
          command: 'npm --version'
      - run:
          name: yarn-version
          command: 'yarn --version'
      - run:
          name: npm-install-global
          command: 'sudo npm install -g bower web-component-tester'
      - run:
          name: yarn-install-global
          command: 'sudo yarn global add gulp-cli'
      - run:
          name: yarn-install
          command: 'yarn install'
      - run:
          name: bower-install
          command: 'bower install'
      - save_cache:
          key: cache-test
          paths:
            - ~/.cache/yarn
            - node_modules
            - bower_components
      - run:
          name: test-integration
          command: 'yarn run test:integration'
  sauce:
    docker:
      - image: circleci/node:6
    steps:
      - checkout
      - restore_cache:
          keys:
            - cache-sauce
      - run:
          name: node-version
          command: 'node --version'
      - run:
          name: npm-version
          command: 'npm --version'
      - run:
          name: yarn-version
          command: 'yarn --version'
      - run:
          name: npm-install-global
          command: 'sudo npm install -g bower web-component-tester'
      - run:
          name: yarn-install-global
          command: 'sudo yarn global add gulp-cli'
      - run:
          name: yarn-install
          command: 'yarn install'
      - run:
          name: bower-install
          command: 'bower install'
      - run:
          name: sauce-download
          command: 'wget https://saucelabs.com/downloads/sc-latest-linux.tar.gz'
      - run:
          name: sauce-install
          command: 'tar -xzf sc-latest-linux.tar.gz'
      - run:
          name: sauce-test
          command: 'yarn run test:sauce'
      - save_cache:
          key: cache-sauce
          paths:
            - ~/.cache/yarn
            - node_modules
            - bower_components
  deploy:
    docker:
      - image: circleci/node:6
    steps:
      - checkout
      - restore_cache:
          keys:
            - cache-deploy
      - run:
          name: node-version
          command: 'node --version'
      - run:
          name: npm-version
          command: 'npm --version'
      - run:
          name: yarn-version
          command: 'yarn --version'
      - run:
          name: npm-install-global
          command: 'sudo npm install -g bower'
      - run:
          name: yarn-install-global
          command: 'sudo yarn global add gulp-cli'
      - run:
          name: yarn-install
          command: 'yarn install'
      - run:
          name: bower-install
          command: 'bower install'
      - run:
          name: build
          command: 'yarn run build'
      - run:
          name: chmod-deploy
          command: 'chmod +x scripts/deploy_circle.sh'
      - run:
          name: deploy
          command: './scripts/deploy_circle.sh'
      - save_cache:
          key: cache-deploy
          paths:
            - ~/.cache/yarn
            - node_modules
            - bower_components
workflows:
  version: 2
  build_and_test:
    jobs:
      - lint
      - test
      - sauce
      - deploy:
          type: approval
          requires:
            - lint
            - test
            - sauce
      
