version: 2
jobs: 
  lint:
    docker:
      - image: circleci/node:6
    steps:
      - checkout
      - restore_cache:
          keys:
            - cache-lint-{{ checksum "package.json" }}
            - cache-lint
      - run:
          name: node-version
          command: 'node --version'
      - run:
          name: npm-version
          command: 'npm --version'
      - run:
          name: yarn-version
          command: 'yarn --version'
      - run:
          name: npm-install-global
          command: 'sudo npm install -g bower web-component-tester'
      - run:
          name: yarn-install-global
          command: 'sudo yarn global add gulp-cli'
      - run:
          name: yarn-install
          command: 'yarn install'
      - run:
          name: bower-install
          command: 'bower install'
      - save_cache:
          key: cache-lint-{{ checksum "package.json" }}
          paths:
            - ~/.cache/yarn
            - node_modules
            - bower_components
      - save_cache:
          key: cache-lint
          paths:
            - ~/.cache/yarn
            - node_modules
            - bower_components
      - run: yarn run lint
  test:
    docker:
      - image: circleci/node:6
    steps:
      - checkout
      - restore_cache:
          keys:
            - cache-test-{{ checksum "package.json" }}
            - cache-test
      - run:
          name: node-version
          command: 'node --version'
      - run:
          name: npm-version
          command: 'npm --version'
      - run:
          name: yarn-version
          command: 'yarn --version'
      - run:
          name: npm-install-global
          command: 'sudo npm install -g bower web-component-tester'
      - run:
          name: yarn-install-global
          command: 'sudo yarn global add gulp-cli'
      - run:
          name: yarn-install
          command: 'yarn install'
      - run:
          name: bower-install
          command: 'bower install'
      - run:
          name: test-integration
          command: 'yarn run test:integration'
      - save_cache:
          key: cache-test-{{ checksum "package.json" }}
          paths:
            - ~/.cache/yarn
            - node_modules
            - bower_components
      - save_cache:
          key: cache-test
          paths:
            - ~/.cache/yarn
            - node_modules
            - bower_components
  sauce:
    docker:
      - image: circleci/node:6
    steps:
      - checkout
      - restore_cache:
          keys:
            - cache-sauce-{{ checksum "package.json" }}
            - cache-sauce
      - run:
          name: node-version
          command: 'node --version'
      - run:
          name: npm-version
          command: 'npm --version'
      - run:
          name: yarn-version
          command: 'yarn --version'
      - run:
          name: npm-install-global
          command: 'sudo npm install -g bower web-component-tester'
      - run:
          name: yarn-install-global
          command: 'sudo yarn global add gulp-cli'
      - run:
          name: yarn-install
          command: 'yarn install'
      - run:
          name: bower-install
          command: 'bower install'
      - run:
          name: sauce-download
          command: 'wget https://saucelabs.com/downloads/sc-latest-linux.tar.gz'
      - run:
          name: sauce-install
          command: 'tar -xzf sc-latest-linux.tar.gz'
      - run:
          name: sauce-test
          command: 'yarn run test:sauce'
      - save_cache:
          key: cache-sauce-{{ checksum "package.json" }}
          paths:
            - ~/.cache/yarn
            - node_modules
            - bower_components
      - save_cache:
          key: cache-sauce
          paths:
            - ~/.cache/yarn
            - node_modules
            - bower_components
  deploy:
    docker:
      - image: circleci/node:6
    steps:
      - checkout
      - restore_cache:
          keys:
            - cache-deploy-{{ checksum "package.json" }}
            - cache-deploy
      - run:
          name: node-version
          command: 'node --version'
      - run:
          name: npm-version
          command: 'npm --version'
      - run:
          name: yarn-version
          command: 'yarn --version'
      - run:
          name: npm-install-global
          command: 'sudo npm install -g bower'
      - run:
          name: yarn-install-global
          command: 'sudo yarn global add gulp-cli'
      - run:
          name: yarn-install
          command: 'yarn install'
      - run:
          name: bower-install
          command: 'bower install'
      - run:
          name: build
          command: 'yarn run build'
      - run:
          name: chmod-deploy
          command: 'chmod +x scripts/deploy.sh'
      - run:
          name: deploy
          command: './scripts/deploy.sh'
      - save_cache:
          key: cache-deploy-{{ checksum "package.json" }}
          paths:
            - ~/.cache/yarn
            - node_modules
            - bower_components
      - save_cache:
          key: cache-deploy
          paths:
            - ~/.cache/yarn
            - node_modules
            - bower_components
  lockfile:
    docker:
      - image: circleci/node:6
    steps:
      - checkout
      - restore_cache:
          keys:
            - cache-lockfile-{{ checksum "package.json" }}
            - cache-lockfile
      - run:
          name: node-version
          command: 'node --version'
      - run:
          name: yarn-version
          command: 'yarn --version'
      - run:
          name: yarn-install-global
          command: 'sudo yarn global add greenkeeper-lockfile@1'
      - run:
          name: greenkeeper-lockfile-update
          command: 'greenkeeper-lockfile-update'
      - run:
          name: greenkeeper-lockfile-upload
          command: 'greenkeeper-lockfile-upload'
      - save_cache:
          key: cache-lockfile-{{ checksum "package.json" }}
          paths:
            - ~/.cache/yarn
      - save_cache:
          key: cache-lockfile
          paths:
            - ~/.cache/yarn
workflows:
  version: 2
  build_and_test:
    jobs:
      - lint:
          filters:
            branches:
              ignore:
                - gh-pages
      - test:
          filters:
            branches:
              ignore:
                - gh-pages
      - sauce:
          filters:
            branches:
              ignore:
                - gh-pages
      - approve-production:
          type: approval
          requires:
            - lint
            - test
            - sauce
          filters:
            branches:
              only: deploy
      - deploy:
          requires:
            - approve-production
          filters:
            branches:
              only: deploy
      - lockfile:
          filters:
            branches:
              only:
                - /greenkeeper-.*/
