version: 2
jobs: 
  lint:
    docker:
      - image: circleci/node:6
    steps:
      - checkout
      - restore_cache:
          keys:
            - cache-install
      - run:
          name: npm-install-global
          command: 'sudo npm install -g bower web-component-tester'
      - run:
          name: yarn-install-global
          command: 'sudo yarn global add gulp-cli'
      - run:
          name: yarn-install
          command: 'yarn install'
      - run:
          name: bower-install
          command: 'bower install'
      - save_cache:
          key: cache-install
          paths:
            - ~/.cache/yarn
            - node_modules
            - bower_components
      - run: yarn run lint
  test:
    docker:
      - image: circleci/node:6
    steps:
      - checkout
      - restore_cache:
          keys:
            - cache-install
      - run:
          name: npm-install-global
          command: 'sudo npm install -g bower web-component-tester'
      - run:
          name: yarn-install-global
          command: 'sudo yarn global add gulp-cli'
      - run:
          name: yarn-install
          command: 'yarn install'
      - run:
          name: bower-install
          command: 'bower install'
      - save_cache:
          key: cache-install
          paths:
            - ~/.cache/yarn
            - node_modules
            - bower_components
      - run: yarn run test:integration
workflows:
  version: 2
  build_and_test:
    jobs:
      - lint
      - test
